# Generated by Django 4.2.11 on 2024-05-11 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_subcategories_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
